#!/bin/bash

source ../config

if [ "$BUILD_MODE" == "offline" ]; then
  echo "offline build"
  mkdir -p ~/.m2/repository/
  cp -R projectRepo/* ~/.m2/repository/
  mvn -B -o package -DskipTests
else
  mvn -B package -DskipTests
fi
